-- 製作 STORED PROCEDURE
DELIMITER $$

-- https://chatgpt.com/share/6a4205d6-2bb0-83ee-b63b-912d97e1178f
USE WORLD$$

CREATE PROCEDURE TEST1()
BEGIN
    DROP TABLE IF EXISTS MYCOUNTRY;

    SET @MY_CODE = 'JPN';

    SELECT @POP_VAR := POPULATION
    FROM WORLD.COUNTRY
    WHERE CODE = @MY_CODE;

    CREATE TABLE MYCOUNTRY
    SELECT CODE, NAME, GNP, POPULATION
    FROM WORLD.COUNTRY
    WHERE CODE = @MY_CODE
       OR POPULATION > @POP_VAR
    ORDER BY POPULATION;

END$$

DELIMITER ;



CALL world.test1();