USE WORLD;
CREATE VIEW COUNTRYVIEW AS
  SELECT Continent, region, code, name FROM world.country ORDER BY CONTINENT;

  SELECT NAME, LANGUAGE FROM COUNTRYVIEW,countrylanguage WHERE CODE=COUNTRYCODE;

  CREATE OR REPLACE VIEW COUNTRYVIEW AS SELECT Continent, region, code, name,POPULATION FROM world.country;

  CREATE OR REPLACE VIEW COUNTRYMAXGNP AS SELECT CODE,NAME,GNP FROM WORLD.COUNTRY
  WHERE (REGION, GNP) IN (SELECT REGION,MAX(GNP) FROM WORLD.COUNTRY group by REGION)

SELECT * FROM COUNTRYMAXGNP;

DESC COUNTRYMAXGNP;

-- 建立VIEW 注意以下
-- 同一個資料庫，VIEW名稱不可重複，也不可以與資料表名稱相同
-- VIEW 不可與TRIGGER建立連結

-- 使用VIEW
-- 查詢敘述只能使用已存在的VIEW及TABLE
-- 不可使用TEMPORARY資料表
-- 不可以使用使用PROCEDURE，FUNCTION自訂義變數

CREATE VIEW SCALEVIEW AS
SELECT CO.NAME COUNTRY_NAME, CI.NAME CITY_NAME, CO.POPULATION COUNTRY_POP, CI.POPULATION CITY_POP
FROM WORLD.COUNTRY CO, WORLD.CITY CI WHERE CO.CODE=CI.COUNTRYCODE ;

CREATE VIEW NEW_SCALEVIEW
(COUNTRYNAME,CITYNAME,COUNTRY_POP,CITY_POP) AS
SELECT CO.NAME , CI.NAME , CO.POPULATION , CI.POPULATION
FROM WORLD.COUNTRY CO, WORLD.CITY CI WHERE CO.CODE=CI.COUNTRYCODE ;

--  ALTER VIEW 
ALTER VIEW NEW_SCALEVIEW AS SELECT CO.NAME COUNTRY_NAME, CI.NAME CITY_NAME, CO.POPULATION COUNTRY_POP, CI.POPULATION CITY_POP
FROM WORLD.COUNTRY CO, WORLD.CITY CI WHERE CO.CODE=CI.COUNTRYCODE ;
-
DROP VIEW IF EXISTS NEW_SCALEVIEW;

DESC COUNTRYVIEW;

-- 使用VIEW做資料維護
USE CMDEV;
CREATE VIEW CMDEV.EMPDEPT30_VIEW AS
SELECT EMPNO,ENAME, JOB,MANAGER,HIREDATE,SALARY,COMM FROM CMDEV.EMP WHERE DEPTNO=30;

-- 修改
UPDATE CMDEV.EMPDEPT30_VIEW SET COMM=600 WHERE EMPNO=7844;

-- 刪除
DELETE FROM CMDEV.EMPDEPT30_VIEW WHERE EMPNO=9001;

CREATE OR REPLACE VIEW CMDEV.EMPDEPT30_VIEW AS
SELECT EMPNO,ENAME, JOB,MANAGER,HIREDATE,SALARY,COMM FROM CMDEV.EMP WHERE DEPTNO=30 WITH CHECK OPTION;

INSERT INTO CMDEV.EMPDEPT30_VIEW VALUES (9003,'MEDIATEK','SALESMAN',7698,'2001-01-01',1000,500);

UPDATE CMDEV.EMPDEPT30_VIEW SET COMM=0 WHERE EMPNO=7844;
