<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>Java2026A</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <modules>
        <module>Ch01/P19_Unicode</module>
        <module>Ch02/P14</module>
        <module>Ch02/P15_BIT-LOGIC_AND-OR_XOR</module>
        <module>Ch02/P16_Bitwise_Operator</module>
        <module>Ch02/P23_Operator_Prioirty</module>
        <module>Ch02/P24_Auto_Type_Convert</module>
        <module>Java_Chapgpt/P2-18_Logic_Operaotor</module>
        <module>P24_AutoTypeConvert</module>
        <module>Ch02/P26_F2C_C2F_Convert</module>
        <module>Ch02/P27_BMI_Calculate</module>
        <module>Ch03/p05_if_else</module>
        <module>P07_If_else_pitfail</module>
        <module>Ch03/P11_Three_OPRands</module>
        <module>Ch03/P10_IF_ELSEIF_ELSE</module>
        <module>Ch03/P11-IF-ELESEIF-H2</module>
        <module>Ch03/P12-if-else-eles-both</module>
        <module>Ch03/P13_IF-ELSEIF-ELSE-RANGESCOPE</module>
        <module>P15_Nested_If_Else</module>
        <module>Ch03/P16_Nested_If_else</module>
        <module>Ch03/P18_SWITCH_INTEGER</module>
        <module>Ch03/P19_Switch_IN_String</module>
        <module>Ch03/P20_Switch_In_Char</module>
        <module>Java_Chapgpt/P3-19_Switch_IN_Lamea</module>
        <module>Ch03/P21_For_While_doWhileLoop</module>
        <module>Ch03/P22_Double_For_Loop</module>
        <module>Ch03/P21_ForLoop_ConvertoToDoWhile_Practice</module>
        <module>Ch03/P23_HW</module>
        <module>Ch03/P24_9x9_Table</module>
        <module>P25_Infinate_Loop</module>
        <module>HW/HW0401-1</module>
        <module>HW/HW0401-2</module>
        <module>Ch03/P27_Q2_Triangle</module>
        <module>Ch03/P26_Q1_T2</module>
        <module>P31_foreach_break_continue</module>
        <module>Ch04/P02_Ave_TEMPERATRUE_AarrayApp</module>
        <module>Ch04/P09_Two_Dim_Array</module>
        <module>Ch04/P05_Array_MIn_Max</module>
        <module>Ch04/P07_ReferncceType_alias</module>
        <module>Ch04/P08_Ref_to_Another_Object</module>
    </modules>

    <properties>
        <maven.compiler.source>26</maven.compiler.source>
        <maven.compiler.target>26</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

</project>