<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>Java2026A</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <modules>
        <module>Ch01/P19_Unicode</module>
        <module>Ch02/P14</module>
        <module>Ch02/P15_BIT-LOGIC_AND-OR_XOR</module>
        <module>Ch02/P16_Bitwise_Operator</module>
        <module>Ch02/P23_Operator_Prioirty</module>
        <module>Ch02/P24_Auto_Type_Convert</module>
        <module>Java_Chapgpt/P2-18_Logic_Operaotor</module>
        <module>P24_AutoTypeConvert</module>
        <module>Ch02/P26_F2C_C2F_Convert</module>
        <module>Ch02/P27_BMI_Calculate</module>
        <module>Ch03/p05_if_else</module>
        <module>P07_If_else_pitfail</module>
        <module>Ch03/P11_Three_OPRands</module>
        <module>Ch03/P10_IF_ELSEIF_ELSE</module>
        <module>Ch03/P11-IF-ELESEIF-H2</module>
        <module>Ch03/P12-if-else-eles-both</module>
        <module>Ch03/P13_IF-ELSEIF-ELSE-RANGESCOPE</module>
        <module>P15_Nested_If_Else</module>
        <module>Ch03/P16_Nested_If_else</module>
        <module>Ch03/P18_SWITCH_INTEGER</module>
        <module>Ch03/P19_Switch_IN_String</module>
        <module>Ch03/P20_Switch_In_Char</module>
        <module>Java_Chapgpt/P3-19_Switch_IN_Lamea</module>
        <module>Ch03/P21_For_While_doWhileLoop</module>
        <module>Ch03/P22_Double_For_Loop</module>
        <module>Ch03/P21_ForLoop_ConvertoToDoWhile_Practice</module>
        <module>Ch03/P23_HW</module>
        <module>Ch03/P24_9x9_Table</module>
        <module>P25_Infinate_Loop</module>
        <module>HW/HW0401-1</module>
        <module>HW/HW0401-2</module>
        <module>Ch03/P27_Q2_Triangle</module>
        <module>Ch03/P26_Q1_T2</module>
        <module>P31_foreach_break_continue</module>
        <module>Ch04/P02_Ave_TEMPERATRUE_AarrayApp</module>
        <module>Ch04/P09_Two_Dim_Array</module>
        <module>Ch04/P05_Array_MIn_Max</module>
        <module>Ch04/P07_ReferncceType_alias</module>
        <module>Ch04/P08_Ref_to_Another_Object</module>
        <module>HW/0407EXAM01</module>
        <module>HW/0407EXAM02</module>
        <module>HW/0407EXAM1_2</module>
        <module>HW/HW03_eeed</module>
        <module>Ch05/P04_Max_Method</module>
        <module>Ch05/P5_Obeerver_Stack</module>
        <module>Ch05/P07_Arimetic_Exeception</module>
        <module>Ch05/P08_Throws_Exception</module>
        <module>Ch05/P_Method_Pass_By_Value</module>
        <module>Ch05/P10_Swap_by_Value</module>
        <module>Ch05/P13_StsicMEthod_StaticAttribbute</module>
        <module>P18_Math_Satitc_Trigeometic_Methods</module>
        <module>P22_Lottos_Game</module>
        <module>Ch05/P23_String_Construct</module>
        <module>untP28_String_ComparsionDemo</module>
        <module>Ch06/P02_Class_Declare</module>
        <module>Ch06/P06_Class_Circle</module>
        <module>Ch06/P07_Class_Empployee</module>
        <module>Ch06/P11_OverLoaded_Class</module>
        <module>Ch06/P07_ATM_Practice</module>
        <module>P06_Class2_Circle</module>
        <module>Ch06/P14_Student_CTOR</module>
        <module>Ch06/P18_Inheritance_this_super_CTOR</module>
        <module>HW/iCAP_HW02</module>
        <module>Java_Chapgpt/P7-30_Rectangle_Class</module>
        <module>Java_Chapgpt/P7-30_Rectangel_Teacher</module>
        <module>Ch06/P23_Sales_Demo</module>
        <module>Ch06/P18_this_super_CTOR_practice</module>
        <module>C06/P32_Employee_Salaty_Hourly_Demo</module>
        <module>Java_Chapgpt/P8-28_Coustomer_Static_Demo</module>
        <module>Ch06/P37_Gaemety_Fect_Circel_Strs_Polymotphidm</module>
        <module>Ch06/P49_Final_Class_Mehod_Staitc_Demo</module>
        <module>P52_Abstract_Class_Demo</module>
        <module>Ch06/P57_InterFace_Demo</module>
        <module>HW/iCAP_HW03</module>
        <module>Ch06/P61_Comparable_Interface</module>
        <module>ITS_A/A-3_Prob_9</module>
        <module>ITS_A/A-3_prob_10</module>
        <module>ITS_A/A-3_Prob_11</module>
        <module>ITS_A/A-3_Prob12</module>
        <module>ITS_A/A-3_Prob_13</module>
        <module>ITS_A/A-3_Prob_14</module>
        <module>ITS_A/A-3_Prob_14-2</module>
        <module>ITS_A/P-6_Prob_16</module>
        <module>ITS_A/A-7_Prob_17</module>
        <module>ITS_A/A-8_Prob_19</module>
        <module>A-9_Prob_22</module>
        <module>ITS_A/A-10_Prob_25</module>
        <module>A-1-_Prob_36</module>
        <module>A-17_Prob_38</module>
        <module>ITS_B/B-4_Prob7</module>
        <module>ITS_B/B-4_Prob_8</module>
        <module>ITS_B/B-4_Prob_9</module>
        <module>ITS_B/B-5_Prob_11</module>
        <module>ITS_B/B-7_Prob_14</module>
        <module>Ch07/P03_Method_with_TP</module>
        <module>Ch07/P04_GenericMethod_TP_Constrain</module>
        <module>Ch07/P05_GenericMethod_Comaparabe</module>
        <module>Ch07/P05_Generic_Class_Demo</module>
        <module>Ch07/P07_GenericClass_Declare</module>
    </modules>

    <properties>
        <maven.compiler.source>26</maven.compiler.source>
        <maven.compiler.target>26</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

</project>