from math_operation import *
test()
test()
print(".......1........")
num1 = mul(9,2)
print(f"mul(9,2): {num1}")
num2 = add(9,2)
print(f"add(9,2): {num2}")
num3 = div(9,2)
print(f"div(9,2): {num3}")
print(f"minus(9,2): {num3}")
print(".......2........")
list_num = operations1(9,2)
for value in list_num:
    print(value)
print(".......3........")
print(f"div(9,2): {list_num[2]}")
print(f"add(9,2): {list_num[1]}")
print(f"minus(9,2): {list_num[3]}")
print(f"mul(9,2): {list_num[0]}")
print(".......4........")
num_num1, num_num2, num_num3, num_num4 = operations2(9,2)
print(f"div(9,2): {num_num3}")
print(f"add(9,2): {num_num2}")
print(f"minus(9,2): {num_num4}")
print(f"mul(9,2): {num_num1}")
