DESC cmdev.emp;
SELECT * FROM cmdev.dept;
INSERT INTO cmdev.dept (dname, location, deptno) VALUES ('研發部', '台灣', 1000);
INSERT INTO cmdev.dept  VALUES (1003,'福利部','' );
-- DEFAULT (現在是NULL)
INSERT INTO cmdev.dept  VALUES (1004,'福利部',DEFAULT );
--  
INSERT INTO cmdev.dept  VALUES (1004,'福利部',NULL );

-- IGNORE (不重複)  不重複的資料會被忽略
INSERT IGNORE INTO cmdev.dept  VALUES (1005,'福利部',DEFAULT );

INSERT INTO cmdev.dept  SET DEPTNO=1005, DNAME='福利部', LOCATION=DEFAULT;

-- 多筆資料
INSERT INTO cmdev.dept  VALUES (1007,'公司',DEFAULT ),(1008,'工廠',DEFAULT ),(1009,'協力商','TAINAN' );

SELECT * FROM cmdev.travel;
SELECT * FROM cmdev.travel WHERE empno='7369' and location='CHICAGO';
UPDATE  cmdev.travel  SET counter=counter+1 WHERE empno='7369' AND Location='CHICAGO'
SELECT * FROM cmdev.travel WHERE empno='7369' and location='CHICAGO';

INSERT INTO CMDEV.TRAVEL VALUES ('7369', 'CHICAGO', 1) ON DUPLICATE KEY UPDATE counter = counter + 1;


INSERT INTO CMDEV.TRAVEL VALUES ('7369', 'CHICAGO', 1);

ON DUPLICATE KEY UPDATE
counter = counter + 1;

-- REPLACE (取代)
REPLACE INTO CMDEV.TRAVEL VALUES ('7369', 'CHICAGO', 1);

REPLACE INTO CMDEV.TRAVEL SET DEPTNO=1000 WHERE EMPNO='AAAA' AND LOCATION='YYYYY';


SELECT * FROM CMDEV.EMP;
UPDATE CMDEV.EMP SET SALARY=SALARY+20;

UPDATE CMDEV.EMP SET SALARY=SALARY-20 where DEPTNO=30;

UPDATE CMDEV.EMP SET SALARY=SALARY+99 order by  SALARY LIMIT 3;

UPDATE CMDEV.EMP SET SALARY=SALARY+8 ORDER BY SALARY DEC LIMIT 2;

UPDATE  IGNORE  CMDEV.DEPT SET  DEPTNO=50 WHERE DEPTNO=20;

UPDATE  IGNORE CMDEV.EMP SET SALARY='HELLO',COMM=1000 WHERE EMPNO=7369;

UPDATE  CMDEV.EMP SET SALARY=SALARY+3 WHERE SALARY<=1500 ORDER BY SALARY LIMIT 1;

-- DELETE
SELECT * FROM CMDEV.EMP WHERE EMPNO=7369;

-- INNODB 才有交易紀錄功能
START TRANSACTION;   -- DCL 

-- 刪除員工
DELETE FROM CMDEV.EMP WHERE EMPNO=7369;  -- 有交易紀錄,所以可以回滚

UPDATE CMDEV.EMP SET SALARY=999 WHERE EMPNO=7369;

-- 提交交易,一但COMMIT成功,就無法回滚了
COMMIT; -- DCL (Data Control Language)

-- 回滚
ROLLBACK;  -- DCL

-- 會完全清除,pc會被刪除,但表結構會保留在資料庫中，是無交易紀錄的，所以無法回滚
Truncate Table CMDEV.EMP; 

-- 最後一筆資料的ID
SELECT last_insert_id();